baseURL = "https://www.jdieter.net/"
languageCode = "en-us"
title = "Jonathan Dieter"
theme = "hugo-initio"
publishDir = "docs"
paginate = 2

[params]
    name = "Jonathan Dieter"
    description = "A system administrator with a passion for open source and a love of teaching"
    email = "jdieter@gmail.com"
    phone = "+353 87 706 5944\n+1 360 763 6230"
    address = "10 Assumption Place, Upper Bridge Street\nSkibbereen, Co. Cork, Ireland"
    year = 2018
    background = ""
    favicon = "images/gt_favicon.png"
    DateForm = "January 2, 2006"

    showSubheader = true
    showServices = false
    showRecentWorks = false
    showDownload = false
    showClients = false

    footerEnableContact = true
    footerEnableFollowme = true
    footerEnableTextWidget = false
    footerEnableFormWidget = false

    custom_css = ["css/override.css"]
    staticman_api = "https://www.jdieter.net/staticman/v2/connect/jdieter/jdieter.net"

[mediaTypes]
    [mediaTypes."application/atom"]
        suffix = "xml"

    [outputFormats.Atom]
        mediaType = "application/atom"
        baseName = "index"
        isPlainText = false

[outputs]
    home = [ "HTML", "Atom" ]
    section = [ "HTML", "Atom" ]
    pages = [ "HTML" ]
    taxonomyTerm = [ "HTML" ]
    taxonomy = [ "HTML", "Atom" ]

[[menu.main]]
    name = "home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "posts"
    url = "/posts"
    weight = 2

[[menu.main]]
    name = "about"
    url = "/about"
    weight = 3

#[[menu.main]]
#    name = "projects"
#    url = "/projects/"
#    weight = 2

[params.sharethis]
    property = "123456789012345678901234"
    custom = true

[[params.social]]
    title = "twitter"
    url = "https://twitter.com/jdieter"
    icon = "fa-twitter-square"
    footer = false
    sharethis = true
    network = "twitter"
[[params.social]]
    title = "google+"
    url = "https://plus.google.com/+jdieter"
    icon = "fa-google-plus-square"
    footer = false
    sharethis = true
    network = "googleplus"
[[params.social]]
    title = "linkedin"
    url = "https://www.linkedin.com/in/jonathandieter"
    icon = "fa-linkedin-square"
    footer = true
    sharethis = true
    network = "linkedin"
[[params.social]]
    title = "github"
    url = "https://github.com/jdieter"
    icon = "fa-github"
    footer = true
    sharethis = false
    network = ""
[[params.social]]
    title = "email"
    url = "mailto:jdieter@gmail.com"
    icon = "fa-envelope"
    footer = false
    sharethis = true
    network = "email"
